apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-sample-r-app-deployment-${TESTING_ID}
  namespace: python-sample-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-remote-app
  strategy: {}
  template:
    metadata:
      labels:
        app: python-remote-app
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      containers:
        - name: python-remote
          image: ${IMAGE}
          imagePullPolicy: Always
          args:
            - "sh"
            - "-c"
            - "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python3 manage.py runserver 0.0.0.0:8001 --noreload"
          env:
            - name: "PYTHONPATH"
              value: "/django_remote_app"
            - name: "DJANGO_SETTINGS_MODULE"
              value: "django_remote_service.settings"
          ports:
            - containerPort: 8001
      imagePullSecrets:
        - name: ecr-secret