apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-sample-app-deployment-${TESTING_ID}
  namespace: dotnet-sample-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-sample-app
  strategy: {}
  template:
    metadata:
      labels:
        app: dotnet-sample-app
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: "true"
    spec:
      containers:
        - name: dotnet-frontend
          image: ${IMAGE}
          ports:
            - containerPort: 8080
          env:
            - name: LISTEN_ADDRESS
              value: "0.0.0.0:8080"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: OTEL_DOTNET_AUTO_PLUGINS
              value: "AWS.Distro.OpenTelemetry.AutoInstrumentation.Plugin, AWS.Distro.OpenTelemetry.AutoInstrumentation"
      imagePullSecrets:
        - name: ecr-secret