FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app
COPY . ./
RUN dotnet publish asp_remote_service/*.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
EXPOSE 8081
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "asp_remote_service.dll"]