apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment-${TESTING_ID}
  namespace: sample-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  strategy: {}
  template:
    metadata:
      labels:
        app: sample-app
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: frontend
          image: ${IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: "OTEL_SERVICE_NAME"
              value: "sample-application-${TESTING_ID}"
            - name: "OTEL_INSTRUMENTATION_COMMON_EXPERIMENTAL_CONTROLLER_TELEMETRY_ENABLED"
              value: "true"
      imagePullSecrets:
        - name: ecr-secret