/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("aws.application.signals.test.framework.java-common-conventions")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}
