## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: Apache-2.0

## This workflow aims to run the Application Signals end-to-end tests as a canary to
## test the artifacts for App Signals enablement. It will deploy a sample app and remote
## service on two EC2 instances, call the APIs, and validate the generated telemetry,
## including logs, metrics, and traces.
name: Application Signals Enablement - Java E2E EC2 Canary Testing
on:
  schedule:
    - cron: '*/15 * * * *' # run the workflow every 15 minutes
  workflow_dispatch: # be able to run the workflow on demand

permissions:
  id-token: write
  contents: read

jobs:
  e2e-ec2-default-test:
    strategy:
      fail-fast: false
      matrix:
        aws-region: ['af-south-1','ap-east-1','ap-northeast-1','ap-northeast-2','ap-northeast-3','ap-south-1','ap-south-2','ap-southeast-1',
                     'ap-southeast-2','ap-southeast-3','ap-southeast-4','ca-central-1','eu-central-1','eu-central-2','eu-north-1',
                     'eu-south-1','eu-south-2','eu-west-1','eu-west-2','eu-west-3','il-central-1','me-central-1','me-south-1', 'sa-east-1',
                     'us-east-1','us-east-2', 'us-west-1', 'us-west-2']
    uses: ./.github/workflows/application-signals-java-e2e-ec2-default-test.yml
    secrets: inherit
    with:
      aws-region: ${{ matrix.aws-region }}
      caller-workflow-name: 'appsignals-e2e-ec2-canary-test'

  e2e-ec2-asg-test:
    strategy:
      fail-fast: false
      matrix:
        aws-region: ['af-south-1','ap-east-1','ap-northeast-1','ap-northeast-2','ap-northeast-3','ap-south-1','ap-south-2','ap-southeast-1',
                     'ap-southeast-2','ap-southeast-3','ap-southeast-4','ca-central-1','eu-central-1','eu-central-2','eu-north-1',
                     'eu-south-1','eu-south-2','eu-west-1','eu-west-2','eu-west-3','il-central-1','me-central-1','me-south-1', 'sa-east-1',
                     'us-east-1','us-east-2', 'us-west-1', 'us-west-2']
    uses: ./.github/workflows/application-signals-java-e2e-ec2-asg-test.yml
    secrets: inherit
    with:
      aws-region: ${{ matrix.aws-region }}
      caller-workflow-name: 'appsignals-e2e-ec2-asg-canary-test'

  publish-result:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        aws-region: [ 'us-east-1', 'af-south-1','ap-east-1','ap-northeast-1' ]
    env:
      caller-workflow-name: test222
    steps:
      - name: Wait for 20 minutes
        run: sleep 600

      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: e2e-test-result
          path: ./e2e-test-result/result-${{ matrix.aws-region }}.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.E2E_IAD_TEST_ACCOUNT_ARN }}
          aws-region: us-east-1

      - name: Retrieve account
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids:
            ACCOUNT_ID, region-account/${{ matrix.aws-region }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ secrets.E2E_TEST_ROLE_ARN }}
          aws-region: ${{ matrix.aws-region }}

      - name: Publish metric on test result
        run: |
          result=$(cat ./e2e-test-result/result-${{ matrix.aws-region }}.txt) || true
          echo "Result was $result"

          if [ "$result" = "SUCCESS" ]; then
            aws cloudwatch put-metric-data --namespace 'ADOT/GitHubActions' \
            --metric-name Failure \
            --dimensions repository=${{ github.repository }},branch=${{ github.ref_name }},workflow=$caller-workflow-name \
            --value 0.0 \
            --region ${{ matrix.aws-region }}
          else
            aws cloudwatch put-metric-data --namespace 'ADOT/GitHubActions' \
            --metric-name Failure \
            --dimensions repository=${{ github.repository }},branch=${{ github.ref_name }},workflow=$caller-workflow-name \
            --value 1.0 \
            --region ${{ matrix.aws-region }}
          fi