name: Resource Attributes Test
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  java-ec2-default-e2e-test:
    uses: ./.github/workflows/java-ec2-default-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'test'

  java-ec2-asg-e2e-test:
    uses: ./.github/workflows/java-ec2-asg-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'test'

  java-k8s-e2e-test:
    uses: ./.github/workflows/java-k8s-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'test'

  python-ec2-default-e2e-test:
    uses: ./.github/workflows/python-ec2-default-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'test'

  python-ec2-asg-e2e-test:
    uses: ./.github/workflows/python-ec2-asg-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'test'

  python-k8s-e2e-test:
    needs: [ java-k8s-e2e-test ]
    uses: ./.github/workflows/python-k8s-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'test'

  node-ec2-default-e2e-test:
    uses: ./.github/workflows/node-ec2-default-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'test'

  node-ec2-asg-e2e-test:
    uses: ./.github/workflows/node-ec2-asg-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'test'

  node-k8s-e2e-test:
    needs: [ python-k8s-e2e-test ]
    uses: ./.github/workflows/node-k8s-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'test'

  dotnet-ec2-default-v8-e2e-test:
    uses: ./.github/workflows/dotnet-ec2-default-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'test'
      dotnet-version: '8.0'

  dotnet-ec2-windows-e2e-test:
    uses: ./.github/workflows/dotnet-ec2-windows-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'test'

  dotnet-k8s-e2e-test:
    needs: [ node-k8s-e2e-test ]
    uses: ./.github/workflows/dotnet-k8s-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'test'

  dotnet-ec2-adot-sigv4-test:
    uses: ./.github/workflows/dotnet-ec2-adot-sigv4-test.yml
    secrets: inherit
    with:
      caller-workflow-name: 'test'
  
  dotnet-ec2-asg-test:
    uses: ./.github/workflows/dotnet-ec2-asg-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'test'
  
  dotnet-ec2-nuget-test:
    uses: ./.github/workflows/dotnet-ec2-nuget-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'test'
  
  dotnet-lambda-test:
    uses: ./.github/workflows/dotnet-lambda-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'test'
  
  java-ec2-adot-sigv4-test:
    uses: ./.github/workflows/java-ec2-adot-sigv4-test.yml
    secrets: inherit
    with:
      caller-workflow-name: 'test'
  
  java-ec2-ubuntu-test:
    uses: ./.github/workflows/java-ec2-ubuntu-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'test'
  
  java-lambda-test:
    uses: ./.github/workflows/java-lambda-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'test'
  
  node-ec2-adot-sigv4-test:
    uses: ./.github/workflows/node-ec2-adot-sigv4-test.yml
    secrets: inherit
    with:
      caller-workflow-name: 'test'
  
  # node-lambda-test
  #   uses: ./.github/workflows/node-lambda-test.yml
  #   secrets: inherit
  #   with:
  #     aws-region: us-east-1
  #     caller-workflow-name: 'test'
  
  # python-ec2-adot-sigv4-test
  #   uses: ./.github/workflows/python-ec2-adot-sigv4-test.yml
  #   secrets: inherit
  #   with:
  #     caller-workflow-name: 'test'
  
  # python-lambda-test
  #   uses: ./.github/workflows/python-lambda-test.yml
  #   secrets: inherit
  #   with:
  #     aws-region: us-east-1
  #     caller-workflow-name: 'test'
