## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: Apache-2.0

## This workflow aims to run the Application Signals end-to-end tests as a canary to
## test the artifacts for App Signals enablement. It will deploy the CloudWatch Agent
## Operator and our sample app and remote service onto a native K8s cluster, call the
## APIs, and validate the generated telemetry, including logs, metrics, and traces.
## It will then clean up the cluster and EC2 instance it runs on for the next test run.
name:  App Signals Enablement - E2E K8s Canary Testing
on:
  schedule:
    - cron: '*/15 * * * *' # run the workflow every 15 minutes
  workflow_dispatch: # be able to run the workflow on demand

permissions:
  id-token: write
  contents: read

jobs:
  e2e-eks-test-1:
    strategy:
      fail-fast: false
      matrix:
        aws-region: ['us-east-1']
    uses: ./.github/workflows/appsignals-e2e-metric-limiter-test.yml
    secrets: inherit
    with:
      aws-region: ${{ matrix.aws-region }}
      test-cluster-name: 'e2e-metric-limiter-test'
      caller-workflow-name: 'appsignals-e2e-metric-limiter-test'