## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: Apache-2.0

## This workflow aims to run the Application Signals DotNet end-to-end tests as a canary to
## test the artifacts for Application Signals enablement. It will deploy a sample app and remote
## service onto an EKS cluster, call the APIs, and validate the generated telemetry,
## including logs, metrics, and traces.
name: Dotnet EKS Windows Enablement Canary Testing
on:
  schedule:
    - cron: '30 9 * * *' # run the workflow every day at 2:30am
  workflow_dispatch: # be able to run the workflow on demand

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read


jobs:
  eks-windows:
    strategy:
      fail-fast: false
      matrix:
        aws-region: ['us-east-1']
    uses: ./.github/workflows/dotnet-eks-windows-test.yml
    secrets: inherit
    with:
      aws-region: ${{ matrix.aws-region }}
      test-cluster-name: 'eks-windows-manual'
      caller-workflow-name: 'appsignals-dotnet-windows-e2e-eks-canary-test'

  ec2-windows:
    strategy:
      fail-fast: false
      matrix:
        aws-region: [ 'us-east-1']
    uses: ./.github/workflows/dotnet-ec2-windows-retry.yml
    secrets: inherit
    with:
      aws-region: ${{ matrix.aws-region }}
      caller-workflow-name: 'appsignals-dotnet-e2e-ec2-windows-canary-test'