name: Create and publish a Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'terraform/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        canary: [ { repo: 'java-eks', dir: '/terraform/java/eks' },
                  { repo: 'java-ec2-default', dir: '/terraform/java/ec2/default' },
                  { repo: 'java-ec2-asg', dir: '/terraform/java/ec2/asg' },
                  { repo: 'java-k8s', dir: '/terraform/java/k8s' },
                  { repo: 'java-metric-limiter', dir: '/terraform/java/eks' },
                  { repo: 'python-eks', dir: '/terraform/python/eks' },
                  { repo: 'python-ec2-default', dir: '/terraform/python/ec2/default' },
                  { repo: 'python-ec2-asg', dir: '/terraform/python/ec2/asg' },
                  { repo: 'python-k8s', dir: '/terraform/python/k8s' } ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.E2E_IAD_TEST_ACCOUNT_ARN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: v6t6x3y1
          REPOSITORY: ${{ matrix.canary.repo }}
          BUILD_ARG: TERRAFORM_DIR=${{ matrix.canary.dir }}
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG --build-arg $BUILD_ARG .
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG