## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: Apache-2.0

## This workflow aims to run the Application Signals end-to-end tests as a canary to
## test the artifacts for App Signals enablement. It will deploy a sample app and remote
## service onto an EKS cluster, instrumented using an OTel Collector built through
## OTel Collector Builder (OCB) and interacting with the OTLP endpoint for this use case.
## Logs, metrics, and traces are all validated.
name: Java EKS OTLP/OCB Enablement Canary Test
on:
  schedule:
    - cron: '12,37 * * * *' # run the workflow at 12th and 37th minute of every hour
  workflow_dispatch: # be able to run the workflow on demand

permissions:
  id-token: write
  contents: read

jobs:
  eks:
    strategy:
      fail-fast: false
      matrix:
        aws-region: ['us-east-1']
        # TODO: Reintroduce all regions
        # aws-region: ['af-south-1','ap-east-1','ap-northeast-1','ap-northeast-2','ap-northeast-3','ap-south-1','ap-south-2','ap-southeast-1',
        #              'ap-southeast-2','ap-southeast-3','ap-southeast-4','ca-central-1','eu-central-1','eu-central-2','eu-north-1',
        #              'eu-south-1','eu-south-2','eu-west-1','eu-west-2','eu-west-3','il-central-1','me-central-1','me-south-1', 'sa-east-1',
        #              'us-east-1','us-east-2','us-west-1','us-west-2']
    uses: ./.github/workflows/java-eks-otlp-ocb-retry.yml
    secrets: inherit
    with:
      aws-region: ${{ matrix.aws-region }}
      test-cluster-name: 'e2e-java-otlp-ocb-canary-test'
      caller-workflow-name: 'appsignals-java-e2e-eks-otlp-ocb-canary-test'
      java-version: '11'
