## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: Apache-2.0

# This is a reusable workflow for running the Enablement test for App Signals.
# It is meant to be called from another workflow.
# Read more about reusable workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview
name: Java EKS Retry
on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      test-cluster-name:
        required: true
        type: string
      caller-workflow-name:
        required: true
        type: string

concurrency:
  group: 'java-eks-${{ inputs.aws-region }}-${{ github.ref_name }}'
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  java-eks-attempt-1:
    uses: ./.github/workflows/java-eks-test.yml
    secrets: inherit
    with:
      aws-region: ${{ inputs.aws-region }}
      test-cluster-name: ${{ inputs.test-cluster-name }}
      caller-workflow-name: ${{ inputs.caller-workflow-name }}

  java-eks-attempt-2:
    needs: [ java-eks-attempt-1 ]
    if: ${{ needs.java-eks-attempt-1.outputs.job-started != 'true' }}
    uses: ./.github/workflows/java-eks-test.yml
    secrets: inherit
    with:
      aws-region: ${{ inputs.aws-region }}
      test-cluster-name: ${{ inputs.test-cluster-name }}
      caller-workflow-name: ${{ inputs.caller-workflow-name }}

  publish-metric-attempt-1:
    needs: [ java-eks-attempt-1, java-eks-attempt-2 ]
    if: always()
    uses: ./.github/workflows/enablement-test-publish-result.yml
    secrets: inherit
    with:
      aws-region: ${{ inputs.aws-region }}
      caller-workflow-name: ${{ inputs.caller-workflow-name }}
      validation-result: ${{ needs.java-eks-attempt-1.outputs.validation-result || needs.java-eks-attempt-2.outputs.validation-result }}

  publish-metric-attempt-2:
    needs: [ java-eks-attempt-1, java-eks-attempt-2, publish-metric-attempt-1 ]
    if: ${{ always() && needs.publish-metric-attempt-1.outputs.job-started != 'true' }}
    uses: ./.github/workflows/enablement-test-publish-result.yml
    secrets: inherit
    with:
      aws-region: ${{ inputs.aws-region }}
      caller-workflow-name: ${{ inputs.caller-workflow-name }}
      validation-result: ${{ needs.java-eks-attempt-1.outputs.validation-result || needs.java-eks-attempt-2.outputs.validation-result }}