## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: Apache-2.0

# This is a reusable workflow for running the Enablement test for App Signals.
# It is meant to be called from another workflow.
# Read more about reusable workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview
name: Node Lambda Retry
on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      caller-workflow-name:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  node-lambda-attempt-1:
    uses: ./.github/workflows/node-lambda-test.yml
    secrets: inherit
    with:
      aws-region: ${{ inputs.aws-region }}
      caller-workflow-name: ${{ inputs.caller-workflow-name }}

  node-lambda-attempt-2:
    needs: [ node-lambda-attempt-1 ]
    if: ${{ needs.node-lambda-attempt-1.outputs.job-started != 'true' }}
    uses: ./.github/workflows/node-lambda-test.yml
    secrets: inherit
    with:
      aws-region: ${{ inputs.aws-region }}
      caller-workflow-name: ${{ inputs.caller-workflow-name }}

  # TODO: will publish metrics after data quality issue is fixed
#  publish-metric-attempt-1:
#    needs: [ node-lambda-attempt-1, node-lambda-attempt-2 ]
#    if: always()
#    uses: ./.github/workflows/enablement-test-publish-result.yml
#    secrets: inherit
#    with:
#      aws-region: ${{ inputs.aws-region }}
#      caller-workflow-name: ${{ inputs.caller-workflow-name }}
#      validation-result: ${{ needs.node-lambda-attempt-1.outputs.validation-result || needs.node-lambda-attempt-2.outputs.validation-result }}
#
#  publish-metric-attempt-2:
#    needs: [ node-lambda-attempt-1, node-lambda-attempt-2, publish-metric-attempt-1 ]
#    if: ${{ always() && needs.publish-metric-attempt-1.outputs.job-started != 'true' }}
#    uses: ./.github/workflows/enablement-test-publish-result.yml
#    secrets: inherit
#    with:
#      aws-region: ${{ inputs.aws-region }}
#      caller-workflow-name: ${{ inputs.caller-workflow-name }}
#      validation-result: ${{ needs.node-lambda-attempt-1.outputs.validation-result || needs.node-lambda-attempt-2.outputs.validation-result }}