## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: Apache-2.0

name: App Signals Enablement - ECR Springboot Sample App Deployment
on:
  push:
  workflow_dispatch: # be able to run the workflow on demand

permissions:
  id-token: write
  contents: read

jobs:
  upload-main-service-image:
    strategy:
      fail-fast: false
      matrix:
        aws-region: [ 'us-west-1' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.E2E_IAD_TEST_ACCOUNT_ARN }}
          aws-region: us-east-1

      - name: Test
        if: ${{ inputs.aws-region == 'us-west-1'}}
        run: echo ACCOUNT_ID="${{ secrets.TEMP_US_WEST_1_ACCOUNT }}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ secrets.E2E_TEST_ROLE_ARN }}
          aws-region: ${{ matrix.aws-region }}

      - name: Update ECR URI
        working-directory: sample-apps/springboot
        run: |
          sed -i 's#"<ECR_IMAGE_LINK>:<TAG>"#"${{ env.ACCOUNT_ID }}.dkr.ecr.${{ matrix.aws-region }}.amazonaws.com/${{ secrets.APP_SIGNALS_E2E_FE_SA_IMG }}:latest"#g' build.gradle.kts

      - name: Upload Main Service Image
        working-directory: sample-apps/springboot
        run: gradle jib

  upload-remote-service-image:
    strategy:
      fail-fast: false
      matrix:
        aws-region: [ 'us-west-1' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.E2E_IAD_TEST_ACCOUNT_ARN }}
          aws-region: us-east-1

      - name: Test
        if: ${{ inputs.aws-region == 'us-west-1'}}
        run: echo ACCOUNT_ID="${{ secrets.TEMP_US_WEST_1_ACCOUNT }}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ secrets.E2E_TEST_ROLE_ARN }}
          aws-region: ${{ matrix.aws-region }}

      - name: Update ECR URI
        working-directory: sample-apps/springboot-remote-service
        run: |
          sed -i 's#"<ECR_IMAGE_LINK>:<TAG>"#"${{ env.ACCOUNT_ID }}.dkr.ecr.${{ matrix.aws-region }}.amazonaws.com/${{ secrets.APP_SIGNALS_E2E_RE_SA_IMG }}:latest"#g' build.gradle.kts

      - name: Upload Remote Service Image
        working-directory: sample-apps/springboot-remote-service
        run: gradle jib

