## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: Apache-2.0

## This workflow aims to run the Application Signals DotNet end-to-end tests as a canary to
## test the artifacts for Application Signals enablement. It will deploy a sample app and remote
## service onto an EKS cluster, call the APIs, and validate the generated telemetry,
## including logs, metrics, and traces.
name: Dotnet EKS Test
on:
  # schedule:
  #   - cron: '4,29 * * * *' # run the workflow at 4th and 29th minute of every hour
  # workflow_dispatch: # be able to run the workflow on demand
  push:
    branches:
      - rename-remote-service

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read


jobs:
  eks:
    strategy:
      fail-fast: false
      matrix:
        aws-region: ['us-east-1']
    uses: ./.github/workflows/dotnet-eks-retry.yml
    secrets: inherit
    with:
      aws-region: ${{ matrix.aws-region }}
      test-cluster-name: 'e2e-playground'
      caller-workflow-name: 'appsignals-dotnet-e2e-eks-canary-test'